# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0.30

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:9000"